/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_host_restart_restart_restart_result$schema = z.object({
  'ok': z.boolean(),
  'message': z.string(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-host-restart',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-host-restart#restart/restart',
      service: 'restart',
      namespace: 'restart',
      method: 'restart',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-host-restart/types#RestartAck',
        schema: _deepseek_ai_dsh_host_restart_restart_restart_result$schema,
      },
      sourceLocation: {"file":"packages/host/restart/src/index.ts","line":133,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
