/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { RestartAck } from '@deepseek-ai/dsh-host-restart/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$72657374617274 {
    restart: () => Promise<RemoteResult<RestartAck>>
  }
  interface TypertRemoteMap {
    'restart/restart': () => Promise<RemoteResult<RestartAck>>
  }
  interface TypertRemoteNamespaceMap {
    'restart': TypertRemoteNamespace$72657374617274
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
